[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/VividCortex/ewma"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/godaemon"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/safefile"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/dlog"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-minisign"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/xsecretbox"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/service"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
