[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/VividCortex/ewma"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/godaemon"

[[constraint]]
  branch = "master"
  name = "github.com/agl/ed25519"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "16.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/safefile"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/pidfile"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/dlog"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-clocksmith"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/go-minisign"

[[constraint]]
  branch = "master"
  name = "github.com/jedisct1/xsecretbox"

[[constraint]]
  name = "github.com/k-sone/critbitgo"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/service"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"
