server_names = ['odohtarget', 'odohrelay']
listen_addresses = ['127.0.0.1:5300']

[query_log]
file = 'query.log'

[static]
  [static.'odohtarget']
  stamp = 'sdns://BQcAAAAAAAAADWRvaC5jcnlwdG8uc3gKL2Rucy1xdWVyeQ'

  [static.'odohrelay']
  stamp = 'sdns://hQcAAAAAAAAAAAAab2RvaC1yZWxheS5lZGdlY29tcHV0ZS5hcHABLw'

[anonymized_dns]
routes = [
    { server_name='odohtarget', via=['odohrelay'] }
]